#! /bin/sh

rm -R $HOME/.gnome2/gedit/plugins/autocomplete
mkdir -p $HOME/.gnome2/gedit/plugins/autocomplete
cp -v -f ./autocomplete/*.py $HOME/.gnome2/gedit/plugins/autocomplete
cp -v -f autocomplete.gedit-plugin $HOME/.gnome2/gedit/plugins
cp -v -f -r ./icons $HOME/.local/share
